services:
  - type: web
    name: fop-tron
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
